# Generated by Django 4.2 on 2025-04-09 01:11

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TrackedEntity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "identifier_type",
                    models.CharField(
                        choices=[
                            ("IMEI", "IMEI Number"),
                            ("PHONE", "Phone Number"),
                            ("SIM", "SIM Card"),
                            ("MAC", "MAC Address"),
                            ("IP", "IP Address"),
                            ("EMAIL", "Email"),
                            ("SOCIAL", "Social Media Handle"),
                        ],
                        max_length=20,
                    ),
                ),
                ("identifier_value", models.CharField(max_length=255)),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("PERSON", "Person"),
                            ("DEVICE", "Device"),
                            ("VEHICLE", "Vehicle"),
                        ],
                        max_length=10,
                    ),
                ),
                ("first_seen", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "verbose_name_plural": "Tracked Entities",
                "unique_together": {("identifier_type", "identifier_value")},
            },
        ),
        migrations.CreateModel(
            name="TrackingRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "warrant_id",
                    models.CharField(
                        max_length=50,
                        validators=[django.core.validators.MinLengthValidator(10)],
                    ),
                ),
                ("legal_basis", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Approval"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("COMPLETED", "Completed"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("entities", models.ManyToManyField(to="tracking.trackedentity")),
                (
                    "requester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "permissions": [
                    ("can_approve_request", "Can approve tracking requests")
                ],
            },
        ),
    ]
